language: ruby
rvm:
 - 2.4.1
env:
  - DB=postgresql
before_install:
  gem install rake -v '12.2.1'
script:
  - bundle exec rake spec
before_script:
  - bundle exec rake db:create RACK_ENV=test
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
