# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ee8cc42d3040e6be987fc2bef3c017c96bb9b8c5d773bf2273b23e1ce28d37b00205cab93fc15727c4de2cc8185066cd2f3fdd0bc3660ecf80e80c2649ac968

test:
  secret_key_base: bd35c24d69a7a95fc9204cee623273e38ce8c2fe35fe4737e101e31cdd3d12263c0fde14a8b6395f673acee65aa6ca3db894f9f9f052fc956829e63ffcbd15b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
